#
# 同步上游仓库或者清理发布都需要用REPO_TOKEN密匙
#
# 记住，同步上游是不会同步您任何自建文件夹的，所以同步后您要自己对比我现有的文件夹里面diy-part.sh和settings.ini文件有没有更新
#
# REPO_TOKEN密匙制作教程：https://git.io/jm.md
#


name: 同步上游仓库
on:
  workflow_dispatch:
    inputs:
      again-fork:
        description: '[fork-actions]改成[fork],再按[Run workflow]按钮启动,开启同步上游仓库'
        required: false
        default: 'fork-actions'

env:
  BILDYML: synchronization.yml
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  del_runs:
    runs-on: Ubuntu-20.04
    name: 同步上游仓库
    
    steps:
    - name: 准备结束
      uses: actions/checkout@v2
      
    - name: 部署环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update > /dev/null 2>&1
        sudo -E apt-get -qq install -y git subversion git-core wget curl grep > /dev/null 2>&1
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
          
    - name: 整理数据
      run: |
        cd $GITHUB_WORKSPACE
        mkdir -p ${GITHUB_WORKSPACE}/openwrt
        cp -Rf `find ./ -maxdepth 1 -type d ! -path './openwrt' ! -path './'` openwrt
        cp -Rf "./.github" "${GITHUB_WORKSPACE}/openwrt"
        git clone -b main https://github.com/281677160/build-actions.git shangyou
        cp -Rf "${GITHUB_WORKSPACE}/shangyou/LICENSE" "${GITHUB_WORKSPACE}/openwrt/LICENSE"
        cp -Rf "${GITHUB_WORKSPACE}/shangyou/README.md" "${GITHUB_WORKSPACE}/openwrt/README.md"
        rm -rf ${GITHUB_WORKSPACE}/shangyou/build/*/.config
        for X in $(find ${GITHUB_WORKSPACE}/openwrt/build -name "diy-part.sh" |sed 's/\/diy-part.sh//g'); do mv "${X}"/diy-part.sh "${X}"/diy-part.sh.bak; done
        for X in $(find ${GITHUB_WORKSPACE}/openwrt/build -name "settings.ini" |sed 's/\/settings.ini//g'); do mv "${X}"/settings.ini "${X}"/settings.ini.bak; done
        for X in $(grep "\"LEDE\"" -rl "${GITHUB_WORKSPACE}/openwrt/build" |grep "settings.ini" |sed 's/\/settings.*//g' |uniq); do cp -Rf shangyou/build/Lede_source/* "${X}"; done
        for X in $(grep "\"LIENOL\"" -rl "${GITHUB_WORKSPACE}/openwrt/build" |grep "settings.ini" |sed 's/\/settings.*//g' |uniq); do cp -Rf shangyou/build/Lienol_source/* "${X}"; done
        for X in $(grep "\"IMMORTAL\"" -rl "${GITHUB_WORKSPACE}/openwrt/build" |grep "settings.ini" |sed 's/\/settings.*//g' |uniq); do cp -Rf shangyou/build/Mortal_source/* "${X}"; done
        for X in $(grep "\"TIANLING\"" -rl "${GITHUB_WORKSPACE}/openwrt/build" |grep "settings.ini" |sed 's/\/settings.*//g' |uniq); do cp -Rf shangyou/build/Tianling_source/* "${X}"; done
        cp -Rf $GITHUB_WORKSPACE/shangyou/build/openwrt_amlogic/* ${GITHUB_WORKSPACE}/openwrt/build/openwrt_amlogic/
        cp -Rf $GITHUB_WORKSPACE/shangyou/.github/workflows/* "${GITHUB_WORKSPACE}/openwrt/.github/workflows"
        cd ${GITHUB_WORKSPACE}/openwrt
        
    - name: SSH远程连接（制作.config配置文件）
      uses: danshui-git/debugger-action@master
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    - name: 整理数据
      run: |
        git add .
        git commit -m "同步上游281677160/build-actions于$(date +%Y年%m月%d号%H时%M分%S秒)"
        git push --quiet "https://${{ secrets.REPO_TOKEN }}@github.com/${{github.repository}}" HEAD:main
        echo "同步完成，请注意查看[diy-part.sh]和[settings.ini]文件的变化和设置好!"
